### ISSUE TITLE
pre-trained checkpoint download link

### ISSUE THREAD

**Issue by Amelia47** [lemuria-wchen/DialogVED#4]
I have met some difficulity in downloading the checkpoint of pre-trained model. So, I would like to ask if there could be any access  of download link of [dialogved_standard.pt] in Baidu Net Disk.

**Comment by lemuria-wchen** [comment]
Thank you for your attention to our work, we will upload these checkpoints to Baidu Netdisk, and we will notify you as soon as possible after completion.

**Comment by Amelia47** [comment]
> 

Thanks a lot !

**Comment by lemuria-wchen** [comment]
> > 
> 
> Thanks a lot !

Hi! Baidu Netdisk link is ready. You can download it whenever you need it. 

link: https://pan.baidu.com/s/13jxHgtScBXnp1KGovJ9EVg 
extraction code: jybd

**Comment by Amelia47** [comment]
Thank you so much ！It helped a lot !
